import { ACCUMULATED, NUMBER, HOURS } from './constants'

export const dummyProjects = [
    {
        id: 1,
        title: 'Project Alpha',
        icon: '⩙',
        goaltype: ACCUMULATED,
        goalMetric: 'Pages',
        hourPerUnity: 0.5,
        timePerMetric: 30,
        weeklyTargetType: HOURS,
        progressType: ACCUMULATED,
        // progress: 750,
        deadline: true,
        deadlineDate: '20.08.2026',
        weeklyCommitment: 10,
        status: 3,
        subProjects: [
            {
                id: 11,
                title: 'Subproject Alpha-1',
                icon: '⩙',
                goaltype: ACCUMULATED,
                goalMetric: 'Pages',
                hourPerUnity: 0.5,
                goal: 500,
                progressType: ACCUMULATED,
                progress: 100,
                deadline: true,
                deadlineDate: '15.05.2026',
                weeklyCommitment: 5,
                status: 2,
                subProjects: [
                    {
                        id: 111,
                        title: 'Subproject Alpha-1-1',
                        icon: '⩙',
                        goaltype: NUMBER,
                        goalMetric: 'Pages',
                        hourPerUnity: 0.5,
                        goal: 200,
                        progressType: NUMBER,
                        progress: 50,
                        deadline: true,
                        deadlineDate: '01.05.2026',
                        weeklyCommitment: 2,
                        status: 1,
                    },
                ]
            },
            {
                id: 12,
                title: 'Subproject Alpha-2',
                icon: '⩙',
                goaltype: NUMBER,
                goalMetric: 'Pages',
                hourPerUnity: 0.5,
                goal: 500,
                progressType: NUMBER,
                progress: 400,
                deadline: true,
                deadlineDate: '20.08.2026',
                weeklyCommitment: 5,
                status: 2,
            },
        ]
    },
    {
        id: 2,
        title: 'Project Beta',
        icon: '⩥',
        goaltype: NUMBER,
        goalMetric: 'Pages',
        hourPerUnity: 0.5,
        goal: 500,
        progress: 150,
        deadline: true,
        deadlineDate: '15.09.2026',
        weeklyCommitment: 5,
        status: 1,
    },
    {
        id: 3,
        title: 'Project Gamma',
        icon: '⩦',
        goaltype: NUMBER,
        goalMetric: 'Pages',
        hourPerUnity: 0.5,
        goal: 840,
        progress: 750,
        deadline: true,
        deadlineDate: '15.09.2026',
        weeklyCommitment: 1,
        status: 2,
    }
]
